import type { Metadata } from "next";
import logosaas from '../assets/images/logosaas.png'
import localFont from "next/font/local";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

  const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
  });

  const dmSans = localFont({
    src: './fonts/DMSans-VariableFont_opsz,wght.woff', 
    variable: '--font-dm-sans',   
    weight: '100 900',             
    style: 'italic',               
  });

export const metadata: Metadata = {
  title: "Anisaas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href={logosaas.src} type="image/x-icon" />
      <body
        className={`${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
